## Structured Data Cleaning

In this notebook we will apply generic transformations to our structured datasets stored in MinIO. Specifically, we will clean and normalize the data (standardizing column names, handling missing values, and normalizing text fields such as case and whitespace), while ensuring consistency across all collections before analysis. All transformations will be performed using Apache Spark for distributed processing, with the final cleaned results stored back into MongoDB.

**Importing Useful Libraries**

In [1]:
import os
import re
import ast
import boto3
from pyspark.sql import SparkSession
from pyspark.sql import functions as F
from pyspark.sql.types import *
import pandas as pd
import numpy as np
from dotenv import load_dotenv
from pymongo import MongoClient

# Load .env file
load_dotenv()

# Read environment variables
endpoint = os.getenv("MINIO_ENDPOINT")
access_key = os.getenv("MINIO_ACCESS_KEY")
secret_key = os.getenv("MINIO_SECRET_KEY")

In [2]:
# Setup S3 client for MinIO (MinIO implements Amazon S3 API)
s3 = boto3.client(
    "s3",
    endpoint_url=endpoint, # MinIO API endpoint
    aws_access_key_id=access_key, # User name
    aws_secret_access_key=secret_key, # Password
)

# Connect to MongoDB
client = MongoClient("mongodb://mongo:mongo@mongo:27017")
db = client["trusted_zone_structured"]

# Setup SparkSession
spark = SparkSession.builder \
    .appName("trusted_zone-structured") \
    .master("spark://spark-master:7077") \
    .config("spark.jars.packages",
            "org.apache.hadoop:hadoop-aws:3.3.4,com.amazonaws:aws-java-sdk-bundle:1.12.262") \
    .config("spark.hadoop.fs.s3a.endpoint", endpoint) \
    .config("spark.hadoop.fs.s3a.path.style.access", "true") \
    .config("spark.hadoop.fs.s3a.connection.ssl.enabled", "false") \
    .config("spark.hadoop.fs.s3a.access.key", access_key) \
    .config("spark.hadoop.fs.s3a.secret.key", secret_key) \
    .config("spark.hadoop.fs.s3a.aws.credentials.provider",
            "org.apache.hadoop.fs.s3a.SimpleAWSCredentialsProvider") \
    .config("spark.hadoop.fs.s3a.connection.maximum", "50") \
    .config("spark.hadoop.fs.s3a.threads.max", "50") \
    .config("spark.hadoop.fs.s3a.connection.timeout", "60000") \
    .config("spark.hadoop.fs.s3a.connection.establish.timeout", "60000") \
    .getOrCreate()

In [3]:
# Due to version mismatches, some variables have values like 60s that need to be normalized
conf = spark.sparkContext._jsc.hadoopConfiguration()
for item in conf.iterator():
    k = item.getKey()
    v = item.getValue()

    # normalize only simple cases like "60s" → "60"
    if isinstance(v, str):
        if v.endswith("s") or v.endswith("h"):
            digits = "".join(c for c in v if c.isdigit())
            conf.set(k, digits)

**Applying Transformations**

Next, we will use Spark to read the files from MinIO and apply some generic transformations on Parquet files. After that, we import them into MongoDB. The following functions can help us do some generic transformations on the data.

In [4]:
# ----------------------------
# CLEAN COLUMN NAMES
# ----------------------------
def clean_column(name):
    name = name.encode("ascii", "ignore").decode()
    name = name.lower().strip()
    name = re.sub(r"[^\w]+", "_", name)
    name = re.sub(r"_+", "_", name)
    return name.strip("_")

# ----------------------------
# CLEAN TABLE NAMES
# ----------------------------
def clean_table_name(name):
    name = name.replace("-", "_")
    name = re.sub(r"[^a-zA-Z0-9_]", "_", name)
    return name.lower()

# ----------------------------
# PERIOD NORMALIZATION (KEEP ONLY THIS VERSION)
# ----------------------------
def normalize_period_column(df, col):

    if col not in df.columns:
        return df

    x = F.lower(F.col(col))

    x = F.regexp_replace(x, r"[^\w\s\-]", "-")
    x = F.regexp_replace(x, r"-+", "-")
    x = F.trim(x)

    return df.withColumn(
        col,
        F.when(x.isNull(), None)
         .otherwise(x)
    )

In [5]:
# LIST ALL "FOLDERS"
response = s3.list_objects_v2(
    Bucket="landing-zone",
    Prefix="persistent-landing/structured/",
    Delimiter="/"
)

folders = []
for prefix in response.get("CommonPrefixes", []):
    path = prefix["Prefix"]

    # exclude unwanted folders
    if "raw" in path or "file_catalog" in path:
        continue

    folders.append(path)

datasets = {}

# PROCESS EACH DATASET
for folder in folders:

    raw_table_name = folder.split('/', 3)[2]
    table_name = clean_table_name(raw_table_name)

    print(f"\nProcessing: {table_name}")

    # 1. Read parquet
    df = spark.read.parquet(f"s3a://landing-zone/{folder}")

    # 2. Drop duplicates
    df = df.dropDuplicates()

    # 3. Standardize column names
    df = df.toDF(*[clean_column(c) for c in df.columns])

    # 4. Fix period/month column
    for c in ["months", "month", "period"]:
        if c in df.columns:
            df = normalize_period_column(df, c)

    # 5. Schema cleanup
    string_cols = [f.name for f in df.schema.fields if isinstance(f.dataType, StringType)]
    for c in string_cols:
        df = df.withColumn(c, F.lower(F.trim(F.col(c))))

    # 6. Conversion point
    pdf = df.toPandas()
    pdf = pdf.where(pd.notna(pdf), None)
    records = pdf.to_dict("records")
    collection = db[table_name]

    # 7. Clean insert
    if records:
        collection.delete_many({})

        batch_size = 5000
        for i in range(0, len(records), batch_size):
            collection.insert_many(records[i:i + batch_size], ordered=False)

    print(f"Loaded {table_name}: {len(records)} rows")

Processing: co2_emission_by_vehicles_1777660672026
Loaded co2_emission_by_vehicles_1777660672026: 6282 rows

Processing: global_warming_dataset_1777660672092
Loaded global_warming_dataset_1777660672092: 100000 rows

Processing: natural_disaster_tweets_1777661000633
Loaded natural_disaster_tweets_1777661000633: 127540 rows

Processing: temperature_change_1777661000821
Loaded temperature_change_1777661000821: 9656 rows

In [6]:
# Check inserted collections
db = client["trusted_zone_structured"]
print(db.list_collection_names())

['global_warming_dataset_1777660672092', 'co2_emission_by_vehicles_1777660672026', 'temperature_change_1777661000821', 'natural_disaster_tweets_1777661000633']

**Showing Transformed Data**

In [16]:
name = next(c for c in db.list_collection_names()
            if c.startswith("co2_emission_by_vehicles"))
df = pd.DataFrame(list(db[name].find({}, {"_id": 0})))
df.head(5)

,make,model,vehicle_class,engine_size_l,cylinders,transmission,fuel_type,fuel_consumption_city_l_100_km,fuel_consumption_hwy_l_100_km,fuel_consumption_comb_l_100_km,fuel_consumption_comb_mpg,co2_emissions_g_km
0,bmw,activehybrid 7l,full-size,3.0,6,a8,z,10.5,7.6,9.2,31,212
1,bmw,x6 xdrive50i,suv - standard,4.4,8,a8,z,16.4,11.3,14.1,20,324
2,cadillac,cts-v coupe,mid-size,6.2,8,as6,z,19.7,12.9,16.6,17,382
3,honda,ridgeline awd,pickup truck - standard,3.5,6,a5,x,15.2,11.3,13.4,21,308
4,kia,soul,station wagon - small,1.6,4,a6,x,9.8,7.9,8.9,32,205

In [18]:
name = next(c for c in db.list_collection_names()
            if c.startswith("global_warming"))
df = pd.DataFrame(list(db[name].find({}, {"_id": 0})))
df.head(5)

,country,year,temperature_anomaly,co2_emissions,population,forest_area,gdp,renewable_energy_usage,methane_emissions,sea_level_rise,...,waste_management,per_capita_emissions,industrial_activity,air_pollution_index,biodiversity_index,ocean_acidification,fossil_fuel_usage,energy_consumption_per_capita,policy_score,average_temperature
0,country_41,1928,-0.876631,6.475424e+08,6.709389e+08,13.080266,3.407885e+12,19.189534,1.113522e+06,13.065625,...,67.309287,9.521487,50.463423,59.913299,92.174283,8.320624,61.931767,3965.409819,50.002123,0.656628
1,country_181,1994,1.975792,5.624029e+07,2.650367e+08,16.640081,9.205250e+12,72.849104,3.968051e+06,26.914859,...,64.042569,2.328607,24.610669,222.238895,78.059211,8.018291,84.107226,3702.122304,20.974063,-6.742663
2,country_94,1959,-0.046595,9.088235e+08,7.060134e+08,85.369889,5.481313e+11,56.592200,2.958762e+06,-4.805219,...,88.826658,7.710164,78.429071,128.159426,61.676545,8.039112,71.679447,4106.408178,75.449175,34.769860
3,country_105,2000,-1.165144,9.370459e+08,7.128588e+08,30.886640,5.181305e+12,53.867992,9.665266e+06,32.606897,...,34.473976,14.778174,99.977358,178.204563,40.082871,8.471874,44.808872,3512.050969,62.099961,34.983485
4,country_186,2014,-1.432683,1.706594e+07,3.362495e+08,94.387485,6.394685e+12,53.906423,9.196585e+06,34.959113,...,78.166820,7.952367,2.968431,107.313050,74.503013,8.181511,91.802846,4464.417446,84.303656,37.540680

In [20]:
name = next(c for c in db.list_collection_names()
            if c.startswith("natural_disaster_tweets"))
df = pd.DataFrame(list(db[name].find({}, {"_id": 0})))
df.head(5)

,tweet_id,tweet_text,disaster_type,hashtags,emojis
0,7.311968e+17,#fortmacfire evacuees are getting help they ne...,wildfire,"['fortmacfire', 'loveit', 'albertastrong', 'pr...",[]
1,7.287663e+17,.@classified to donate profits from his new si...,wildfire,[],[]
2,7.300928e+17,important information for displaced residents ...,wildfire,"['ymmfire', 'albertafires']",[]
3,7.294406e+17,ottawa to match #redcross donations for #fortm...,wildfire,"['redcross', 'fortmcmurray']",[]
4,7.297647e+17,rt @pwrdf: many thanks to all of you who have ...,wildfire,['fortmcmurray'],[]

In [21]:
name = next(c for c in db.list_collection_names()
            if c.startswith("temperature_change"))
df = pd.DataFrame(list(db[name].find({}, {"_id": 0})))
df.head(5)

,area_code,area,months_code,months,element_code,element,unit,y1961,y1962,y1963,...,y2010,y2011,y2012,y2013,y2014,y2015,y2016,y2017,y2018,y2019
0,7,angola,7016,dec-jan-feb,7271,temperature change,°c,0.035,-0.106,-0.247,...,0.728,0.331,-0.191,1.038,0.593,1.223,1.602,0.529,0.848,1.473
1,258,anguilla,7006,june,6078,standard deviation,°c,0.379,0.379,0.379,...,0.379,0.379,0.379,0.379,0.379,0.379,0.379,0.379,0.379,0.379
2,30,antarctica,7007,july,7271,temperature change,°c,0.016,-0.316,0.497,...,0.563,2.243,-0.903,1.304,-0.843,-1.439,-1.894,0.185,1.512,1.561
3,26,brunei darussalam,7005,may,6078,standard deviation,°c,0.269,0.269,0.269,...,0.269,0.269,0.269,0.269,0.269,0.269,0.269,0.269,0.269,0.269
4,26,brunei darussalam,7019,sep-oct-nov,6078,standard deviation,°c,0.227,0.227,0.227,...,0.227,0.227,0.227,0.227,0.227,0.227,0.227,0.227,0.227,0.227

We have nested lists in the columns `hashtags` and `emojis` of the collection `natural_disaster_tweets`, but due to the high number of labels, we decided not to flatten them into new columns.

In [23]:
# Print the number of unique elements in a nested column
def print_num_unique_labels(df, column):

    def parse_cell(x):
        if pd.isna(x):
            return []

        if isinstance(x, list):
            return x

        if isinstance(x, str):
            try:
                return ast.literal_eval(x)
            except:
                cleaned = x.replace("[", "").replace("]", "").replace("'", "")
                return [i.strip() for i in cleaned.split(",") if i.strip()]

        return []

    all_tags = df[column].apply(parse_cell).explode()
    all_tags = all_tags.dropna().astype(str).str.strip().str.lower()

    print(f"Number of unique labels in {column}: {all_tags.nunique()}")

# Get collection natural_disaster_tweets
name = next(c for c in db.list_collection_names()
            if c.startswith("natural_disaster_tweets"))
df = pd.DataFrame(list(db[name].find({}, {"_id": 0})))

print_num_unique_labels(df, "hashtags")
print_num_unique_labels(df, "emojis")

Number of unique labels in hashtags: 27550
Number of unique labels in emojis: 713