## Semi-structured Data Cleaning

In this notebook we will apply generic transformations to our semi-structured datasets stored in MinIO. Specifically, we will clean and normalize the data, ensuring consistency in field names, handling missing or null values by assigning appropriate defaults where required, and normalizing text fields such as case and whitespace. All transformations will be performed using Apache Spark for distributed processing, with the final cleaned results stored back into MongoDB.

**Importing Useful Libraries**

In [1]:
import os
import re
import ast
import json
import boto3
from pyspark.sql import SparkSession
from pyspark.sql import functions as F
from pyspark.sql.types import *
import pandas as pd
import numpy as np
from dotenv import load_dotenv
from pymongo import MongoClient

# Load .env file
load_dotenv()

# Read environment variables
endpoint = os.getenv("MINIO_ENDPOINT")
access_key = os.getenv("MINIO_ACCESS_KEY")
secret_key = os.getenv("MINIO_SECRET_KEY")

In [2]:
# Setup S3 client for MinIO (MinIO implements Amazon S3 API)
s3 = boto3.client(
    "s3",
    endpoint_url=endpoint, # MinIO API endpoint
    aws_access_key_id=access_key, # User name
    aws_secret_access_key=secret_key, # Password
)

# Connect to MongoDB
client = MongoClient("mongodb://mongo:mongo@mongo:27017")
db = client["trusted_zone_semi-structured"]

# Setup SparkSession
spark = SparkSession.builder \
    .appName("trusted_zone-structured") \
    .master("spark://spark-master:7077") \
    .config("spark.jars.packages",
            "org.apache.hadoop:hadoop-aws:3.3.4,com.amazonaws:aws-java-sdk-bundle:1.12.262") \
    .config("spark.hadoop.fs.s3a.endpoint", endpoint) \
    .config("spark.hadoop.fs.s3a.path.style.access", "true") \
    .config("spark.hadoop.fs.s3a.connection.ssl.enabled", "false") \
    .config("spark.hadoop.fs.s3a.access.key", access_key) \
    .config("spark.hadoop.fs.s3a.secret.key", secret_key) \
    .config("spark.hadoop.fs.s3a.aws.credentials.provider",
            "org.apache.hadoop.fs.s3a.SimpleAWSCredentialsProvider") \
    .config("spark.hadoop.fs.s3a.connection.maximum", "50") \
    .config("spark.hadoop.fs.s3a.threads.max", "50") \
    .config("spark.hadoop.fs.s3a.connection.timeout", "60000") \
    .config("spark.hadoop.fs.s3a.connection.establish.timeout", "60000") \
    .getOrCreate()

In [3]:
# Due to version mismatches, some variables have values like 60s that need to be normalized
conf = spark.sparkContext._jsc.hadoopConfiguration()
for item in conf.iterator():
    k = item.getKey()
    v = item.getValue()

    # normalize only simple cases like "60s" → "60"
    if isinstance(v, str):
        if v.endswith("s") or v.endswith("h"):
            digits = "".join(c for c in v if c.isdigit())
            conf.set(k, digits)

**Applying Transformations**

Next, we will use Spark to read the files from MinIO and apply some generic transformations on Parquet files. After that, we import them into MongoDB. The following functions can help us do some generic transformations on the data.

In [4]:
# ----------------------------
# CLEAN COLUMN NAMES
# ----------------------------
def clean_column(name):
    name = name.encode("ascii", "ignore").decode()
    name = name.lower().strip()
    name = re.sub(r"[^\w]+", "_", name)
    name = re.sub(r"_+", "_", name)
    return name.strip("_")

# ----------------------------
# CLEAN TABLE NAMES
# ----------------------------
def clean_table_name(name):
    name = name.replace("-", "_")
    name = re.sub(r"[^a-zA-Z0-9_]", "_", name)
    return name.lower()

# ----------------------------
# PERIOD NORMALIZATION (KEEP ONLY THIS VERSION)
# ----------------------------
def normalize_period_column(df, col):

    if col not in df.columns:
        return df

    x = F.lower(F.col(col))

    x = F.regexp_replace(x, r"[^\w\s\-]", "-")
    x = F.regexp_replace(x, r"-+", "-")
    x = F.trim(x)

    return df.withColumn(
        col,
        F.when(x.isNull(), None)
         .otherwise(x)
    )

In [6]:
# LIST ALL "JSONS"
response = s3.list_objects_v2(
    Bucket="landing-zone",
    Prefix="persistent-landing/semistructured/",
    Delimiter="/"
)

json_files = []

for obj in response.get("Contents", []):
    key = obj["Key"]

    if key.endswith(".json") and not key.endswith("/"):
        json_files.append(key)

datasets = {}

# PROCESS EACH DATASET
for json_file in json_files:

    raw_table_name = json_file.split("/")[-1].replace(".json", "")
    table_name = clean_table_name(raw_table_name)

    print(f"\nProcessing: {table_name}")

    # airquality_barcelona is ARRAY<ARRAY<STRUCT>>
    if table_name != "airquality_barcelona":

        # 1. Read JSON with Spark
        df = spark.read.option("multiline", "true").json(
            f"s3a://landing-zone/{json_file}"
        )
        
        # 2. Standardize column names
        df = df.toDF(*[clean_column(c) for c in df.columns])
    
        # 3. Fill missing required fields (schema safety)
        for col in df.columns:
            df = df.withColumn(col, F.coalesce(F.col(col), F.lit(None)))
    
        # 4. Normalize string fields
        string_cols = [
            f.name for f in df.schema.fields
            if isinstance(f.dataType, StringType)
        ]
    
        for c in string_cols:
            df = df.withColumn(c, F.lower(F.trim(F.col(c))))

        # 6. Convert to Mongo format
        pdf = df.toPandas()
        pdf = pdf.where(pd.notna(pdf), None)
        records = pdf.to_dict("records")
        collection = db[table_name]
    
        # 7. Mongo insert
        if records:
            collection.delete_many({})
    
            batch_size = 5000
            for i in range(0, len(records), batch_size):
                collection.insert_many(records[i:i + batch_size], ordered=False)
    
        print(f"Loaded {table_name}: {len(records)} rows")

    else:

        raw = spark.read.text(f"s3a://landing-zone/{json_file}")
        json_str = raw.select(F.concat_ws("", F.collect_list("value"))).first()[0]
        data = json.loads(json_str)
        
        # ================================
        # STEP 1: remove wrapper if needed
        # ================================
        if isinstance(data, list) and len(data) > 0 and isinstance(data[0], list):
            snapshots = data
        else:
            snapshots = [data]
        
        # ================================
        # STEP 2: FLATTEN ALL SNAPSHOTS
        # ================================
        stations = []
        
        for snapshot in snapshots:
            if isinstance(snapshot, list):
                for station in snapshot:
                    stations.append(station)
            else:
                stations.append(snapshot)
        
        print("snapshots:", len(snapshots))
        print("stations:", len(stations))
        
        # ================================
        # STEP 3: OPTIONAL NORMALIZATION (SAFE)
        # ================================
        def normalize(r):
            out = {}
            for k, v in r.items():
                if isinstance(v, (dict, list)):
                    out[k] = json.dumps(v, ensure_ascii=False)
                else:
                    out[k] = v
            return out
        
        stations = [normalize(s) for s in stations]
        
        # ================================
        # STEP 4: STORE IN MONGO
        # ================================
        records = stations
        collection = db[table_name]
        
        if records:
            collection.delete_many({})  # remove if you want full refresh
        
            batch_size = 5000
            for i in range(0, len(records), batch_size):
                collection.insert_many(records[i:i + batch_size], ordered=False)
        
        print(f"Loaded {table_name}: {len(records)} stations inserted")

Processing: airquality_barcelona
snapshots: 9
stations: 27
Loaded airquality_barcelona: 27 stations inserted

Processing: weather_barcelona
Loaded weather_barcelona: 9 rows

**Showing Transformed Data**

In [7]:
name = next(c for c in db.list_collection_names()
            if c.startswith("airquality_barcelona"))
df = pd.DataFrame(list(db[name].find({}, {"_id": 0})))
df.head(5)

,id,name,locality,timezone,country,owner,provider,isMobile,isMonitor,instruments,sensors,coordinates,licenses,bounds,distance,datetimeFirst,datetimeLast
0,2990,BARCELONA (PARC DE LA VALL D'HEBRON),BARCELONA,Europe/Madrid,"{""id"": 67, ""code"": ""ES"", ""name"": ""Spain""}","{""id"": 4, ""name"": ""Unknown Governmental Organi...","{""id"": 70, ""name"": ""EEA""}",False,True,"[{""id"": 2, ""name"": ""Government Monitor""}]","[{""id"": 7566, ""name"": ""co µg/m³"", ""parameter"":...","{""latitude"": 41.426099999937115, ""longitude"": ...","[{""id"": 10, ""name"": ""ODC-BY"", ""attribution"": {...","[2.147999999784839, 41.426099999937115, 2.1479...",None,"{""utc"": ""2016-11-17T23:00:00Z"", ""local"": ""2016...","{""utc"": ""2026-02-09T15:00:00Z"", ""local"": ""2026..."
1,3273,BARCELONA (CIUTADELLA),BARCELONA,Europe/Madrid,"{""id"": 67, ""code"": ""ES"", ""name"": ""Spain""}","{""id"": 4, ""name"": ""Unknown Governmental Organi...","{""id"": 70, ""name"": ""EEA""}",False,True,"[{""id"": 2, ""name"": ""Government Monitor""}]","[{""id"": 4274503, ""name"": ""no µg/m³"", ""paramete...","{""latitude"": 41.38639999987508, ""longitude"": 2...","[{""id"": 10, ""name"": ""ODC-BY"", ""attribution"": {...","[2.1874000003484873, 41.38639999987508, 2.1874...",None,"{""utc"": ""2016-11-17T23:00:00Z"", ""local"": ""2016...","{""utc"": ""2026-02-09T15:00:00Z"", ""local"": ""2026..."
2,3276,Barcelona,Barcelona,Europe/Madrid,"{""id"": 67, ""code"": ""ES"", ""name"": ""Spain""}","{""id"": 4, ""name"": ""Unknown Governmental Organi...","{""id"": 16, ""name"": ""Catalonia Medi Ambient I S...",False,True,"[{""id"": 2, ""name"": ""Government Monitor""}]","[{""id"": 7526, ""name"": ""co µg/m³"", ""parameter"":...","{""latitude"": 41.398724, ""longitude"": 2.1533988}","[{""id"": 38, ""name"": ""CC0 1.0"", ""attribution"": ...","[2.1533988, 41.398724, 2.1533988, 41.398724]",None,"{""utc"": ""2016-11-17T23:00:00Z"", ""local"": ""2016...","{""utc"": ""2026-05-01T02:00:00Z"", ""local"": ""2026..."
3,2990,BARCELONA (PARC DE LA VALL D'HEBRON),BARCELONA,Europe/Madrid,"{""id"": 67, ""code"": ""ES"", ""name"": ""Spain""}","{""id"": 4, ""name"": ""Unknown Governmental Organi...","{""id"": 70, ""name"": ""EEA""}",False,True,"[{""id"": 2, ""name"": ""Government Monitor""}]","[{""id"": 7566, ""name"": ""co µg/m³"", ""parameter"":...","{""latitude"": 41.426099999937115, ""longitude"": ...","[{""id"": 10, ""name"": ""ODC-BY"", ""attribution"": {...","[2.147999999784839, 41.426099999937115, 2.1479...",None,"{""utc"": ""2016-11-17T23:00:00Z"", ""local"": ""2016...","{""utc"": ""2026-02-09T15:00:00Z"", ""local"": ""2026..."
4,3273,BARCELONA (CIUTADELLA),BARCELONA,Europe/Madrid,"{""id"": 67, ""code"": ""ES"", ""name"": ""Spain""}","{""id"": 4, ""name"": ""Unknown Governmental Organi...","{""id"": 70, ""name"": ""EEA""}",False,True,"[{""id"": 2, ""name"": ""Government Monitor""}]","[{""id"": 4274503, ""name"": ""no µg/m³"", ""paramete...","{""latitude"": 41.38639999987508, ""longitude"": 2...","[{""id"": 10, ""name"": ""ODC-BY"", ""attribution"": {...","[2.1874000003484873, 41.38639999987508, 2.1874...",None,"{""utc"": ""2016-11-17T23:00:00Z"", ""local"": ""2016...","{""utc"": ""2026-02-09T15:00:00Z"", ""local"": ""2026..."

In [8]:
name = next(c for c in db.list_collection_names()
            if c.startswith("weather_barcelona"))
df = pd.DataFrame(list(db[name].find({}, {"_id": 0})))
df.head(5)

,interval,is_day,temperature,time,weathercode,winddirection,windspeed
0,900,1,17.4,2026-05-01t18:30,3,89,14.0
1,900,1,17.2,2026-05-01t18:45,3,90,13.3
2,900,1,17.2,2026-05-01t18:45,3,90,13.3
3,900,1,17.2,2026-05-01t18:45,3,90,13.3
4,900,0,17.2,2026-05-01t21:00,80,68,9.7